### ISSUE TITLE
missing i2b2 1.7

### ISSUE THREAD

**Issue by dckc** [tfmorris/i2b2#1]
in particular, Version: 1.7.05 released May 11, 2015

(this is largely just a way of saying hello... this thing looks nice; is it still maintained?)

**Comment by tfmorris** [comment]
Thanks for letting me know.  Since the i2b2 team only announces releases to their private "academic users" list, the only way I have of finding out about them is polling their web site.

With respect to maintenance, are you asking about i2b2 or this repo?  i2b2 is still maintained by Harvard to the best of my knowledge, although their level of support is tied to the grants they are able to maintain.  The repo is something I set up to help me track i2b2 when I was considering taking on a client with an interest in i2b2.  I've continued to maintain it as a public resource since it doesn't take much time, but I'm hopeful that some day i2b2 will grow up into a "real" open source project and have a public source repo of their own instance of distributing source snapshots.  They are NIH-funded, after all.

I think there's a fair amount of i2b2-expertise around, outside of the i2b2 team, but there's no focal point for it to coalesce around to share bug fixes, enhancements, etc, which I think is a shame.

**Comment by tfmorris** [comment]
Oops, just realized that this repo doesn't have *any* of the 1.7 versions.  I definitely have at least a few of those loaded up somewhere.  I'll see if I can track them down and merge them in.

**Comment by dckc** [comment]
I'm asking about this repo.

I should have given some context. I'm in the medical informatics division at KU Med Center, and our [HERON](https://informatics.kumc.edu/work/wiki/HERON) project has been based on i2b2 since 2010. I'm on the i2b2 academic users list. There was an i2b2 meeting at Harvard recently and there was some discussion of using github and such. I went looking and found your repository.

**Comment by tfmorris** [comment]
Sorry I never got around to finding the time to do this.

It looks like the i2b2 team has (finally) created open-source repos for their software.  They're split across multiple repos in two different organizations (not sure why) at:  https://github.com/i2b2 and https://github.com/i2b2plugins.

I'll suggest that they include the historical context (perhaps they don't know about the SVN/CVS/etc to GIT conversion tools that make it easy to do this).  If they can't/won't, I'll leave this open until I get a chance to incorporate 1.7 sources to provide a bridge to the official repo.

My repo is an artifact of some investigatory research that I did before taking on a client a few years ago, it's unlikely to receive any additional attention unless I take on additional i2b2 clients.

BTW, KUMC was the type of center of i2b2 expertise that I was referring to when talking about more effective knowledge sharing across the i2b2 community.

**Comment by tfmorris** [comment]
I've added everything that I had up through 1.7.04.  I don't claim it's perfect, but it should at least provide historical context for those interested in it until the i2b2 team gets the full source history online.

**Comment by dckc** [comment]
Good stuff. Thanks.
